[project]
name = 'Decentralized-Supply-Chain-Finance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.payment]
path = 'contracts/payment.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-registry]
path = 'contracts/product-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.tracking]
path = 'contracts/tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
